name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install libncurses5-dev
    - name: make
      run: make
